language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
    - cargo install --force rustfmt

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo fmt --verbose -- --check
