language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
    - (cargo install rustfmt || true)
    - PATH=$PATH:/home/travis/.cargo/bin

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo fmt --verbose -- --check
