[package]
name = "fletcher"
version = "1.0.0"
authors = ["Joseph Angelo <b.j.angelo@gmail.com>"]
description = "A dependency free implementation of the Fletcher's checksum algorithm"
repository = "https://github.com/jbangelo/fletcher"
documentation = "https://docs.rs/fletcher/"
readme = "README.md"
keywords = ["fletcher", "checksum"]
categories = ["algorithms", "no-std"]
license = "MIT"
edition = "2024"

[dependencies]
ux = {  version = "^0.1", optional = true }

[dev-dependencies]
byteorder = "^1.3"
quickcheck = "^1"

[features]
u48checksum = [ "dep:ux" ]

