name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '@weekly'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [ stable, nightly ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        overrides: true
        components: rustfmt, clippy
    - name: Formatting
      run: cargo fmt --verbose -- --check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
